from metahtml.property.timestamp.__common__ import TimestampExtractor

class Extractor(TimestampExtractor):
    jsonpaths = [
        ( 'en.antaranews.com',              '$.datePublished' ),
        ( 'wusa9.com',                      '$.datePublished' ),
        ( 'wfaa.com',                       '$.datePublished' ),
        ( 'news.sky.com',                   '$.datePublished' ),
        ( 'king5.com',                      '$.datePublished' ),
        ( 'kens5.com',                      '$.datePublished' ),
        ( 'fox61.com',                      '$.datePublished' ),
        ( '13newsnow.com',                  '$.datePublished' ),
        ( 'onenewspage.us',                 '$.datePublished' ),
        ( 'onenewspage.us',                 '$."@graph"[*].datePublished' ),

        ( 'realcleardefense.com',           '$.disabled' ), # disabled due to large number of documents with incorrect timestamps in the LD+JSON

        ( None, '$.datePublished'),
        ( None, '$.uploadDate'),
        ( None, '$.dateCreated'),
        ( None, '$.temporal'),
        ( None, '$."@graph"[*].datePublished'),
        ( None, '$."@graph"[*].uploadDate'),
        ( None, '$."@graph"[*].dateCreated'),
        ( None, '$."@graph"[*].temporal'),
        ]

    xpaths = [

        # custom xpaths
        ( 'aapb.co.jp',                     '//div[@class="post-date"]/span'),
        ( 'abc57.com',                      '//div[@class="content-date-posted"]/text()'),
        ( 'abcnews.go.com',                 '//meta[@itemprop="uploadDate"]/@content'),
        ( 'abcnews.go.com',                 '//meta[@property="lastPublishedDate"]/@content'),
        ( 'accesswdun.com',                 '//div[@class="article-datetime"]/text()'),
        ( 'acton.org',                      '//h3[@class="byline"]/text()'),
        ( 'actu.fr',                        '//time/@datetime'),
        ( 'actu.orange.fr',                 '//div[@class="player-head"]/meta[@itemprop="uploadDate"]/@content'),
        ( 'actualidad.rt.com',              '//div[@class="ArticleView-timestamp"]/time/@datetime' ),
        ( 'addustour.com',                  '//div[@id="al-right"]/div[@class="timestamp"]' ),
        ( 'aftenposten.no',                 '(//time[@itemprop="datePublished"]/@datetime)[1]'),
        ( 'afsa.org',                       '//div[@class="breadcrumb"]/a'), # format is july/august 2017, and so doesn't parse
        ( 'akamai.com',                     '//p[@class="cmp-blog-author__date"]'),
        ( 'algemeiner.com',                 '//div[@class="date"]'),
        ( 'aljazeera.com',                  '//div[@class="article-duration"]/time/@datetime'),
        ( 'allgov.com',                     '//div[@style="clear: both"]'),
        ( 'allgov.com',                     '//span[@class="blog-date"]'),
        ( 'allnewspipeline.com',            '//div[@id="content"]/table//span[@style="font-size: medium;"]'),
        ( 'alt.expresszeitung.com',         '//time/@datetime'),
        ( 'america.aljazeera.com',          '//div[contains(@class,"dateTime")]' ),
        ( 'americanthinker.com',            '//div[@class="article_date"]'),
        ( 'amerikawoche.com',               '//div[@style="float:left; margin-top: 10px;"]/i/text()'),
        ( 'amman.diplo.de',                 '//span[@class="heading__meta"]/text()'),
        ( 'amnesty.org',                    '//time'),
        ( 'amnesty.org',                    '//p[@class="meta"]'),
        ( 'antpedia.com',                   '//div[@class="newsinfo row text-center"]' ),
        ( 'applescoop.org',                 '//*[@class="story-info"]/text()'),
        ( 'arabic.rt.com',                  '//meta[@name="published_time_telegram"]/@content'),
        ( 'archiv.bundesregierung.de',      '//p[@class="date"]/text()'),
        ( 'archiv2017.die-linke.de',        '//time/@datetime'),
        ( 'armscontrolwonk.com',            '//span[@class="date published time"]' ),
        ( 'artgnews.com',                   '(//div[@class="info_area"]/span[@class="date"]/span)[1]' ),
        ( 'article.wn.com',                 '//div[@class="article-source faded"]//span[@class="datestamp"]' ),
        ( 'arxiv.org',                      '//meta[@name="citation_date"]/@content'),
        ( 'as-coa.org',                     '//time[@class="datetime"]/@datetime'),
        ( 'asia.nikkei.com',                '//meta[@name="date"]/@content' ),
        ( 'asiae.co.kr',                    '(//div[@class="articleInfo"]/div/em)[1]'),
        ( 'asiae.co.kr',                    '//meta[@property="article:published_time"]/@content'),
        ( 'asaninst.org',                   '//div[@class="post_date_big"]'),
        ( 'attack.mitre.org',               '//div[@class="col-md-11 pl-0"]/text()'), # FIXME: also has modified, but hard to extract
        ( 'attack.mitre.org',               '//div[@class="row card-data"]'),
        ( 'audit.gov.cn',                   '//meta[@name="publishtime"]/@content'),
        ( 'auto.qq.com',                    '//span[@class="a_time"]'),
        ( 'babylonbee.com',                 '//div[@class="article-date mb-2"]'),
        ( 'badische-zeitung.de',            '//meta[@name="cXenseParse:publishtime"]/@content'),
        ( 'bangkok.today',                  '//time[@class="entry-date published"][@datetime]' ),
        ( 'bangkokpost.com',                '//div[@class="article-info"]/div[@class="row"]/div[1]/p'),
        ( 'bangkokpost.com',                '//div[@class="article-info"]/div[@class="row"]/div[1]/p'),
        ( 'bankinfosecurity.com',           '//span[@class="article-byline"]/span[@class="text-nowrap"]'),
        ( 'baobeibaobei.com',               '//div[@class="news-writer"]/span/text()'),
        ( 'baoquocte.vn',                   '//div[@class="dateUp"]/span[@class="format_time"]'),
        ( 'baotintuc.vn',                   '//meta[@itemprop="datePublished"]/@content'),
        ( 'basnews.com',                    '//span[@class="katzhmer"]'),
        ( 'bbc.co.uk',                      '(//div[@class="date date--v2"])[1]' ),
        ( 'bbc.co.uk',                      '(//div[contains(@class,"date--v2")])[1]' ),
        ( 'bbc.co.uk',                      '//meta[@name="dcterms.created"]/@content'),
        ( 'bbc.com',                        '(//div[@class="date date--v2"])[1]' ),
        ( 'bbc.com',                        '(//div[contains(@class,"date--v2")])[1]' ),
        ( 'bbc.com',                        '//div[@class="mini-info-list__date vxp-date date date--v2"]/@data-datetime'),
        ( 'beijing.gov.cn',                 '(//div[@class="container"]/span)[1]'),
        ( 'beijingcream.com',               '//p[@class="byline vcard"]//time[@class="updated"]' ),
        ( 'beijingcream.com',               '//p[@class="byline vcard"]//time[@class="updated"]/@datetime' ),
        ( 'beijingcream.com',               '//time/@datetime' ),
        ( 'belfercenter.org',               '(//article//div[@class="view-publication-author-and-date"]//span[@class="pub-date"])[1]'),
        ( 'bignewsnetwork.com',             '//article/p[@class="author"]' ),
        ( 'bistum-fulda.de',                '(//span[@style="color: #333333"]/text())[4]'),
        ( 'bits.debian.org',                '//div[@class="content-title"]/text()'),
        ( 'blacklistednews.com',            '//div[@class="col-md-4"]'),
        ( 'blacknews.com',                  '//div[@class="date-header"]'), # FIXME: url blocked from .cache
        ( 'bles.com',                       '(//span[@class="p-time"]/@data-date)[1]' ),
        ( 'blog.charitynavigator.org',      '//h2[@class="date-header"]/span'),
        ( 'blog.goo.ne.jp',                 '//div[@class="article__date"]/span' ),
        ( 'blog.goo.ne.jp',                 '//span[@class="entry-top-info-time"]'),
        ( 'blog.group-ib.com',              '//div[@class="t001__uptitle t-uptitle t-uptitle_sm"]/div[@data-customstyle="yes"]'),
        ( 'blog.paleo.or.jp',               '(//time[@class="entry-date updated"]/@datetime)[1]'),
        ( 'blog.segu-info.com.ar',          '//span[@class="meta_date"]'),
        ( 'blog.talosintelligence.com',     '//h2[@class="date-header"]'),
        ( 'blog.twitter.com',               '//div[@class="second-line"]'),
        ( 'blogs.elpais.com',               '//span[@class="date-header date-int updated"]/@title'),
        ( 'blogs.wsj.com',                  '//meta[@name="article.published"]/@content' ),
        ( 'blogspot.com',                   '//abbr[@class="published"]/@datetime'),
        ( 'blogspot.com',                   '//abbr[@itemprop="datePublished"]/@title'),
        ( 'blogspot.com',                   '//div[@class="columns-inner"]/div[@class="date-outer"]/h2[@class="date-header"]' ),
        ( 'blogspot.com',                   '//h2[@class="date-header"]'), #FIXME: for non-english, it finds the location but can't extract the date
        ( 'blogspot.com',                   '//h2[@class="date-header"]/span'),
        ( 'blogspot.com',                   '//h2[@class="date-header"]/span/text()'),
        ( 'blogspot.com',                   '//h3'),
        ( 'blogspot.com',                   '//span[@class="published updated"]/@title' ),
        ( 'blogspot.com',                   '//time[@class="published"]/@datetime'),
        ( 'bloomberg.com',                  '//meta[@name="parsely-pub-date"]/@content' ),
        ( 'bnews.vn',                       '//div[@style="color:red"]/span[@class="post-time"]'),
        ( 'bnn.de',                         '//time/@datetime'),
        ( 'bondebladet.no',                 '//div[@class="pubdate"]/text()'),
        ( 'brf.be',                         '(//time/text())[1]'),
        ( 'brightside.me',                  '(//meta[@property="article:published_time"]/@content)[1]'),
        ( 'brucefleming.net',               '//p[@class="date"]/text()'),
        ( 'businessinsider.com',            '//div[@data-e2e-name="byline-timestamp"]'),
        ( 'bustle.com',                     '//time/@datetime'),
        ( 'buzzfeednews.com',               '//p[@class="news-article-header__timestamps-posted"]'),
        ( 'campaignforliberty.org',         '//div[@class="post-meta"]'),
        ( 'canada-news.org',                '//time[@class="entry-date published updated"]/@datetime'),
        ( 'canadiandimension.com',          '//article/header/p[@class="byline"]/text()'),
        ( 'carnegieeurope.eu',              '//div[@class="gutter-half-bottom--mobile"]'),
        ( 'cas.cn',                         '//meta[@name="PubDate"]/@content'),
        ( 'cato.org',                       '//div[@class="meta meta--default text-uppercase p-mb-last-child-0"]'),
        ( 'cbc.ca',                         '//time/@datetime'),
        ( 'cbsnews.com',                    '//p[@class="content__meta content__meta-timestamp"]/time/@datetime'),
        ( 'cbsnews.com',                    '//time/@datetime' ),
        ( 'cdrb.com.cn',                    '//div[@class="clearfix"]/div[@class="cb-text"]/span[@id="paperdate"]' ),
        ( 'cer.eu',                         '//span[@class="date-display-single"]'),
        ( 'cjr.org',                        '//section[@id="story-info"]/small'),
        ( 'cjr.org',                        '//section[@id="story-info"]'),
        ( 'cfr.org',                        '//li[@class="cst-issue__list-item"]'),
        ( 'channelb.org',                   '(//time/@datetime)[2]'),
        ( 'charismanews.com',               '//span[@class="published"]/time'),
        ( 'chey.org',                       '//p[@class="mt-20"]/text()'), # finds date, but can't parse
        ( 'chicagotribune.com',             '//meta[@name="date"]/@content'),
        ( 'china.caixin.com',               '//span[@id="pubtime_baidu"]'),
        ( 'chinacdc.cn',                    '//span[@class="info-date"]/text()'),
        ( 'chosonsinbo.com',                '//div[@class="moji_postmeta"]'),
        ( 'churchmilitant.com',             '//div[@class="author"]'),
        ( 'cijua.de',                       '//span[@class="updated rich-snippet-hidden"]/text()'),
        ( 'claremont.today',                '//div[@class="field field--name-field-datetime field--type-datetime field--label-hidden field__items"]/div[@class="field__item"]'),
        ( 'clarin.com',                     '//div[@class="breadcrumb col-lg-6 col-md-12 col-sm-12 col-xs-12"]/span' ),
        ( 'blog.cloudfare.com',             '//p[@class="f3 fw5 gray5 db di-l mt2"]/@datetime'),
        ( 'cma.org.cn',                     '//meta[@name="PubDate"]/@content'),
        ( 'cmagoodrich.org',                '//article[@class="news-detail"]/span[@class="date"]'),
        ( 'cms.bistum-fulda.de',            '(//span[@style="color: #333333"]/text())[4]'),
        ( 'cn.engadget.com',                '//div[@class="Mt(5px) C(engadgetFontLightGray)"]/text()'),
        ( 'cnas.org',                       '//div[@class="attribution-block"]'),
        ( 'cnn.com',                        '(//p[@class="cnnBodyText"])[1]' ),
        ( 'cnn.com',                        '//meta[@*="DATE"]/@content' ),
        ( 'cnn.com',                        '//meta[@*="pubdate"]/@content' ),
        ( 'cnnphilippines.com',             '//div/p[@class="dateString no-icon"]'),
        ( 'conseil-constitutionnel.fr',     '//h1[@class="title"]/span[@class="date"]'),
        ( 'conseil-etat.fr',                '//time/@datetime'),
        ( 'corporate.qiagen.com',           '//div[@class="field-publication-date"]' ),
        ( 'crime-research.org',             '//div[@class="content"]/b'),
        ( 'crofsblogs.typepad.com',         '//h2[@class="date-header"]'),
        ( 'cronicaglobal.elespanol.com',    '(//div[@class="news_ext_date"]/time)[1]'),
        ( 'crp-infotec.de',                 '//meta[@name="revised"]/@content'),
        ( 'csbaonline.org',                 '//div[@class="article-meta"]/time'),
        ( 'csis.org',                       '(//article[@role="article"]/p)[1]' ),
        ( 'csis.org',                       '//div[@class="byline"]' ),
        ( 'cyberctm.com',                   '//div[@class="publish-date"]/text()'),
        ( 'cybersecurity.att.com',          '//div[@class="date"]/text()'),
        ( 'dailyalert.org',                 '//div[@style="margin-left:315px; margin-right:315px;"]/text()'),
        ( 'dailymotion.com',                '//meta[@property="video:release_date"]/@content'),
        ( 'dailyreadlist.com',              '//time/@datetime' ),
        ( 'dailyreadlist.com',              '//time[@itemprop="datePublished"]/@datetime'),
        ( 'dailyreadlist.com',              '//time[class="entry-date date published updated"]'),
        ( 'dailyusapost.com',               '//div[@class="date"]//a[@title="Why the confusion about Kim Jong Un’s well being truly is sensible"]' ),
        ( 'dakaractu.com',                  '//div[@id="date"]' ),
        ( 'dalloz-actualite.fr',            '//span[@class="field-field-published-at"]' ),
        ( 'dalloz-actualite.fr',            '//span[@class="field-field-published-at"]'),
        ( 'dandc.eu',                       '//time[@class="pubdate"]/@datetime'),
        ( 'daressalam.diplo.de',            '//span[@class="heading__meta"]' ),
        ( 'daressalam.diplo.de',            '//span[@class="heading__meta"]' ),
        ( 'daserste.ndr.de',                '//div[@class="last changed small"]' ),
        ( 'daserste.ndr.de',                '//div[@class="last changed small"]' ),
        ( 'databreachtoday.eu',             '//span[@class="text-nowrap"]'),
        ( 'datarepository.wolframcloud.com', '(//ul[@class="source-metadata"]/li/span[@class="property"])[1]'),
        ( 'davidotokiblog.com.ng',          '//div[@class="post-item-inner"]/div[@class="post-meta"]/span[@class="post-date published"]/@datetime'),
        ( 'dcmi.org',                       '(//time/@datetime)[1]'),
        ( 'de.catholicnewsagency.com',      '//div[@class="main_caption"]' ),
        ( 'de.catholicnewsagency.com',      '//div[@class="main_caption"]' ),
        ( 'de.statista.com',                '//span[@class="display-block sectionSubline--statistic width100"]' ),
        ( 'de.statista.com',                '//span[@class="display-block sectionSubline--statistic width100"]' ),
        ( 'de.toonpool.com',                '//div[@clas="siUser"]' ),
        ( 'debate.com.mx',                  '//time[@class="newsfull__time"]/@datetime' ),
        ( 'debate.com.mx',                  '//time[@class="newsfull__time"]/@datetime' ),
        ( 'defamer.gawker.com',             '//time/@datetime' ),
        ( 'defense.gouv.fr',                '//div[@class="mise-a-jour"]'),
        ( 'defense.gouv.fr',                '//div[@class="mise-a-jour"]/text()'),
        ( 'defense.gov',                    '//span[@class="date"]/text()'),
        ( 'defensemaven.io',                '//div[@class="sk4e2855"]/p[@class="skpzhulc skh9fqbk"]/time/@title' ),
        ( 'defensemedianetwork.com',        '//p[@class="author-byline"]/span'),
        ( 'deloitte.com',                   '//span[@class="hidden-xs hidden-sm"]/text()'),
        ( 'den-haag-cw.diplo.de',           '//span[@class="heading__meta"]' ),
        ( 'den-haag-cw.diplo.de',           '//span[@class="heading__meta"]' ),
        ( 'depositphotos.com',              '//div[@class="info-item"]' ),
        ( 'der-farang.com',                 '(//div[@class="article-meta-wrapper"]/span)[2]' ),
        ( 'der-farang.com',                 '(//div[@class="article-meta-wrapper"]/span)[2]' ),
        ( 'deutschelobby.com',              '//time[@class="entry-date published updated"]/@datetime' ),
        ( 'devdiscourse.com',               '//meta[@itemprop="datePublished"]/@content'),
        ( 'dhaka.diplo.de',                 '//span[@class="heading__meta"]' ),
        ( 'diagnostics.roche.com',          '//meta[@name="publishedDate"]/@content'),
        ( 'digima-news.com',                '//div[@class="tak-category clearfix"]/p/text()'),
        ( 'diploweb.com',                   '//div[@class="article"]/h3/text()'),
        ( 'donaldjtrump.com',               '//p[@class="date"]'),
        ( 'driverscloud.com',               '//div[@class="auteur"]'),
        ( 'dschuba.diplo.de',               '//span[@class="heading__meta"] '),
        ( 'duo.com',                        '//time/@datetime'),
        ( 'dw.com',                         '(//ul[@class="smallList"]/li)[1]'),
        ( 'dy.163.com',                     '(//p[@class="time"]/span)[1]'),
        ( 'eaglespeak.us',                  '//h2[@class="date-header"]'),
        ( 'earthreview.net',                '//time[@class="updated"]/@datetime'),
        ( 'eastcoastdaily.in',              '//div[@class="entry-header"]//span[@class="date meta-item"]' ),
        ( 'egamebook.com',                  '//p[@class="meta"]'),
        ( 'ejinsight.com',                  '//span[@class="doctor"]'),
        ( 'elcomercio.com',                 '//meta[@name="cXenseParse:recs:publishtime"]/@content'),
        ( 'eldeber.com.bo',                 '//div[@class="bottom"]/h6/span'),
        ( 'elladodelmal.com',               '//h2[@class="date-header"]'),
        ( 'elnacional.com.do',              '(//time[contains(@class,"entry-date")])[1]' ),
        ( 'elperuano.pe',                   '//article[@class="notatexto"]/p/b' ),
        ( 'empirenews.net',                 '//time[@class="entry-date published updated"]/@datetime' ),
        ( 'en.mediamass.net',               '//time/@datetime' ),
        ( 'en.paperblog.com',               '//div[@class="article-title"]/em' ),
        ( 'en.sahos24.com',                 '//div[@class="news_date_time"]/p' ),
        ( 'en.sahos24.com',                 '//div[@class="news_date_time"]/p' ),
        ( 'engineering.skroutz.gr',         '//time/@datetime'),
        ( 'english.khan.co.kr',             '//div[@class="article_date"]' ),
        ( 'english.kyodonews.net',          '//p[@class="credit"]'),
        ( 'english.sina.com',               '//div[@class="t_attr"]/span' ),
        ( 'erlc.com',                       '//div[@class="date-meta"]'),
        ( 'es.weforum.org',                 '//div[@class="article-published"]'),
        ( 'euobserver.com',                 '//article[@id="article"]/time/@datetime'),
        ( 'eurasiareview.com',              '//time[@class="entry-date published"]/@datetime'),
        ( 'europe1.fr',                     '(//span[@class="publication"]/time/@datetime)[1]'),
        ( 'europe1.fr',                     '(//span[@class="publication"]/time/@datetime)[1]'),
        ( 'eurosurveillance.org',           '//meta[@name="dc.date"]/@content'),
        ( 'extranet.who.int',               '//span[@class="date-display-single"]/@content'),
        ( 'finance.yahoo.com',              '//time[@class="date Fz(11px) Mb(4px)  D(ib)"]'),
        ( 'findingdulcinea.com',            '//div[@id="article_capsule_date"]/text()'),
        ( 'firstpost.com',                  '//span[@class="article-date"]' ),
        ( 'flags.net',                      '//meta[@name="Date-Creation-yyyymmdd"]/@content'),
        ( 'fnad.info',                      '//time[@class="entry-time"]/@datetime' ),
        ( 'fnn.jp',                         '//div[@class="article-header-info__date "]/time[@class="article-header-info__time-wrap"]/@datetime' ),
        ( 'fnn.jp',                         '//time[@class="article-header-info__time-wrap"]/@datetime'),
        ( 'forbes.com',                     '//meta[@property="article:published"]/@content'),
        ( 'foreignaffairs.com',             '//div[@class="DISABLED--forces the use of url timestamps"]' ),
        ( 'foreignpolicy.com',              '(//div[@class="meta-data"])/time' ),
        ( 'fortune.com',                    '//p[@class="articleHeader__publishDate--2TN0F"]/time/@datetime' ),
        ( 'forum.digitalfernsehen.de',      '//span[@class="DateTime"]/@title' ),
        ( 'foxnews.com',                    '//div[@class="article-date"]/time' ),
        ( 'foxnews.com',                    '//meta[@name="dcterms.created"]/@content' ),
        ( 'foxnews.com',                    '//p[@class="published updated dtstamp"]//span[@class="value-title"]/@title' ),
        ( 'fp21.org',                       '//h4'),
        ( 'franceculture.fr',               '//div[@class="cover-content-description-date"]/time/@datetime'),
        ( 'franceculture.fr',               '//time/@datetime' ),
        ( 'frankfurter-hefte.de',           '//span[@class="info-bar__date"]/text()'),
        ( 'fredblog.stlouisfed.org',        '//*[@class="entry-date"]'),
        ( 'freepressjournal.in',            '//div[@class="story-meta-info-m__date-time__1IiJn"]/time/@datetime'),
        ( 'freerepublic.com',               '(//b/span[@class="date"])[1]'),
        ( 'freespeech.org',                 '//div[@class="date"]/p'),
        ( 'freespeechdaily.com',            '//i[@class="fa fa-clock-o"]/a'),
        ( 'fsf.org',                        '//span[@class="documentModified"]'),
        ( 'fsfe.org',                       '//time'),
        ( 'gamemaz.info',                   '//time[@class="entry-time"]/@datetime' ),
        ( 'gawker.com',                     '//div[@class="meta__text"]/time/@datetime'),
        ( 'gela-news.de',                   '//span[@class="post-date"]'),
        ( 'gizchina.com',                   '//article/header//time[@itemprop="datePublished"]/@datetime'),
        ( 'glasnost.de',                    '(//td[@width="*"]/h4)[1]'),
        ( 'globalecho.org',                 '//meta[@name="shareaholic:article_published_time"]/@content'),
        ( 'globalnews.ca',                  '//div[@class="c-byline__date c-byline__date--pubDate"]/span'),
        ( 'globalnews.ca',                  '//div[@class="date-and-time"]' ),
        ( 'globalnews.ca',                  '//div[contains(@class,"c-byline__date")]' ),
        ( 'globalpolicy.org',               '//div[@class="article-content"]/div[0]' ),
        ( 'globalpolicy.org',               '//div[@class="article-content"]/div[1]' ),
        ( 'globalpolicy.org',               '//div[@class="article-content"]/div[2]' ),
        ( 'globalpolicy.org',               '//div[@class="node-article topline"]' ),
        ( 'globalpolicy.org',               '//time' ),
        ( 'globalsecurity.org',             '//div[@id="modified"]'),
        ( 'globaltimes.cn',                 '//div[@class="span7 text-left"]' ),
        ( 'globaltimes.cn',                 '//span[@class="pub_time"]' ),
        ( 'golden-tamatama.com',            '//time[@class="date gf entry-date updated"]/text()'),
        ( 'goldsea.com',                    '//div[@id="credits"]' ),
        ( 'gooseart.net',                   '//time[@class="entry-time"]/@datetime' ),
        ( 'greatsciences.com',              '//div[@class="entry-date"]/span'),
        ( 'guernseypress.com',              '//div[@class=" full pb-feature pb-layout-item pb-f-single-title"]/div/p/time/@datetime'),
        ( 'guernseypress.com',              '//div[@class=" full pb-feature pb-layout-item pb-f-single-title"]/div/p/time/@datetime'),
        ( 'gulfnews.com',                   '//time[@itemprop="datePublished"]/@datetime'),
        ( 'gxzf.gov.cn',                    '//div[@class="article-inf-left"]/text()'),
        ( 'hainanlife.ru',                  '//div[@class="block-right"]/div[@class="date"]' ),
        ( 'headlines.yahoo.co.jp',          '//p[@class="fss ymuiDate"]'),
        ( 'headtopics.com',                 '//meta[@name="date"]/@content' ),
        ( 'healthmedia.com.tw',             '//div[@class="detail_time_box"]/time' ),
        ( 'heavy.com',                      '//meta[@property="article:published_time"]/@content'),
        ( 'heavy.com',                      '//time[@itemprop="datePublished"]/@datetime'),
        ( 'heinrichplatz.tv',               '//span[@class="entry-date"]'),
        ( 'heritage.org',                   '//div[@class="article-general-info"]/text()'),
        ( 'heritage.org',                   '//span[@class="headline__date"]'),
        ( 'hindi.moneycontrol.com',         '//div[@class="a_10mgry PT5"]'),
        ( 'hindi.moneycontrol.com',         '//div[@class="a_10mgry PT5"]'),
        ( 'hirhome.com',                    '(//span[@lang="EN-US"])[2]' ),
        ( 'hist-chron.com',                 '//span[@class="date"]'),
        ( 'hkcnews.com',                    '//div[@class="article-info"]' ),
        ( 'hljxinwen.dbw.cn',               '//div[@align="center"]/text()'),
        ( 'hoaxbuster.com',                 '//div[@class="info_article_page_top"]'),
        ( 'hogueprophecy.com',              '//div[@class="entry-content"]//span[@style="color: #ff0000;"]/strong' ),
        ( 'home.treasury.gov',              '//div[@class="content"]//time/@datetime'),
        ( 'homelandsecuritynewswire.com',   '//span[@class="published"]' ),
        ( 'hospimedia.fr',                  '//div[@class="date-time-mobile"]/time/@datetime'),
        ( 'hotair.com',                     '(//div[@class="col-xs-12 article-text"]/p)[1]'),
        ( 'hotair.com',                     '(//div[@class="col-xs-12 article-text"]/p)[1]'),
        ( 'hotair.com',                     '//meta[@property="article:published_time"]/@content'),
        ( 'hygienes.net',                   '//span[@class="published"]'),
        ( 'icanswitzerland.ch',             '//time[@class="onDate date published"]/@datetime'),
        ( 'icrc.org',                       '//span[@class="small date seperator-left"]'),
        ( 'ict.org.il',                     '//div[@class="article_sum_details"]/text()'),
        ( 'idahopoliticsdaily.com',         '//dd[@class="published"]/time/@datetime'),
        ( 'ietf.org',                       '(//main/div/p)[1]'),
        ( 'imf.org',                        '//meta[@name="Date"]/@content' ),
        ( 'important7.com',                 '//div[@class="post-meta vcard"]//p//span[@class="updated"]' ),
        ( 'in.news.yahoo.com',              '//time[@class="date Fz(11px) Mb(4px)  D(ib)"]/@datetime'),
        ( 'informationclearinghouse.info',  '//div[@class="post-content"]//p/font[@size="5"]' ),
        ( 'informationclearinghouse.info',  '//font[@face="Times New Roman"]/p' ),
        ( 'informationdissemination.net',   '//h2[@class="date-header"]'),
        ( 'infox.ru',                       '//time[@itemprop="datePublished"]/@datetime'),
        ( 'insta.shared.to',                '//p[@class="fs"]' ),
        ( 'instagram-engineering.com',      '//None' ), # FIXME: this should be None
        ( 'intrepidreport.com',             '//span[@class="entry-date"]'),
        ( 'inverse.com',                    '//time/@datetime'),
        ( 'iranchamber.com',                '//td[@class="fontdate"]' ),
        ( 'iris-france.org',                '//div[@class="date"]/text()'),
        ( 'islamsounnah.com',               '//meta[@property="article:published_time"]/@content'),
        ( 'israelnationalnews.com',         '//span[@itemprop="datePublished"]' ),
        ( 'itas.kit.edu',                   '//div[@class="fusszeile"]'),
        ( 'itbiznews.com',                  '(//div[@class="viewTitle"]/dl/dd/text())[2]'),
        ( 'itv.com',                        '//li[@class="labels__item labels__item--time"]/time/@datetime'),
        ( 'ivoox.com',                      '//span[@class="icon-date"]/text()'),
        ( 'izbicki.me',                     '//div[@class="info"]'),
        ( 'jacksonfreepress.com',           '//span[@class="datetime"]'),
        ( 'janes.com',                      '//span[@itemprop="datePublished"]'),
        ( 'japantimes.co.jp',               '//li[@class="post_time"]/time/@datetime'),
        ( 'jawharafm.net',                  '//span[@class="dat_ev"]' ),
        ( 'jawharafm.net',                  '//span[@class="dat_ev"]/text()'),
        ( 'jewishworldreview.com',          '//p[@class="simple"]' ),
        ( 'jiemian.com',                    '//div[@class="article-info"]/p[@class="info-s"]/span[@class="date"]' ),
        ( 'jinde.org',                      '(//div[@class=" am-margin-top-sm"])[3]'),
        ( 'journalofdemocracy.org',         '//div[@class="article__action article__action--issue-date"]/a'),
        ( 'jpost.com',                      '//meta[@itemprop="datePublished"]/@content'),
        ( 'julia-obermeier.de',             '//span[@class="date"]'),
        ( 'justiz.nrw.de',                  '//meta[@name="Date"]/@content'),
        ( 'juventudrebelde.cu',             '//div[@class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-p0 news-date"]/text()'),
        ( 'kaixo.com',                      '//div[@id="edukiak"]/text()'),
        ( 'kake.com',                       '//span[@class="Timestamp-time"]' ),
        ( 'kiezblatt.de',                   '//time[@class="entry-date"]/@datetime'),
        ( 'king5.com',                      '//meta[@itemprop="datePublished"]/@content'),
        ( 'konfliktbearbeitung.net',        '//div[@class="content"]/span[@class="submitted"]'),
        ( 'knightfoundation.org',           '//span[@class="entry-date"]'),
        ( 'koratdaily.com',                 '//h4[@class="grey ita"]'),
        ( 'korea-chair.eu',                 '//span[@class="published"]'),
        ( 'korea-chair.eu',                 '//span[@class="tribe-event-date-start"]'),
        ( 'kr.lnd.com.cn',                  '//div[@id="news_content_title1"]/span/text()'),
        ( 'kr.xinhuanet.com',               '//meta[@property="article:publish_time"]/@content'),
        ( 'krcnr.cn',                       '//meta[@name="publishdate"]/@content'),
        ( 'krebsonsecurity.com',            '//span[@class="date updated"]'),
        ( 'kwcg.ca',                        '//span[@class="xg1"]'),
        ( 'kyoto-np.co.jp',                 '//div[@class="article-header"]/div[@class="article-header__article-ttl-box side-padding"]/time[@class="article-header__article-ttl-item"]/@datetime' ),
        ( 'labs.f-secure.com',              '//p[@class="blog-post-meta"]'),
        ( 'lanl.gov',                       '//div[@id="date"]'),
        ( 'lanl.gov',                       '//h5[@class="text-muted mb-1 pt-2"]'),
        ( 'lanl.gov',                       '//span[@class="d-block d-md-inline-block h5"]'),
        ( 'lapresse.it',                    '//div[@class="article__main__metadata"]/span[@class="article__main__date"]' ),
        ( 'laregion.es',                    '//meta[@name="date"]/@content' ),
        ( 'latestly.com',                   '//span[@class="article_date"]'),
        ( 'laverdad.com',                   '//div[@id="left-sidebar"]/time[@class="fecha"]/@datetime'),
        ( 'lavozdegalicia.es',              '(//meta[@itemprop="datePublished"]/@content)[1]' ),
        ( 'lci.fr',                         '(//time)[1]'),
        ( 'lci.fr',                         '//div[@class="col-full"]/div[@class="article-date-credit-wrapper"]/time/@datetime'),
        ( 'leaders.com.tn',                 '(//div[@class="infos"])[1]' ),
        ( 'leaders.com.tn',                 '//div[@class="col-xs-12 col-sm-8 col-md-8"]/div[@class="infos"]'),
        ( 'learningenglish.voanews.com',    '//div[@class="published"]/span[@class="date"]/time/@datetime' ),
        ( 'lecourrier.vn',                  '//div[@class="newsDetail_time"]/span'),
        ( 'lecourriercauchois.fr',          '//li[@class="detail date"]/text()'),
        ( 'lecranstdenis.org',              '//time/@datetime' ),
        ( 'ledauphine.com',                 '//span[@class="publish"]'),
        ( 'ledevoir.com',                   '//time/@datetime' ),
        ( 'ledevoir.com',                   '//time/@datetime'),
        ( 'legalis.net',                    '//div[@class="date_article_actualite fl"]/text()'),
        ( 'legrandsoir.info',               '//div[@class="article-date  print-only"]' ),
        ( 'lematin.ch',                     '//p[@class="publishedDate"]/text()'),
        ( 'lenouvelliste.ch',               '//div[@class="col-xs-22"]/small/text()'),
        ( 'lessentiel.lu',                  '//div[@class="published clearfix"]/p/text()'),
        ( 'lexexakt.de',                    '//tbody/tr/td[@align="center"]'),
        ( 'lindependant.fr',                '//span[@class="article-detail-infos-published"]/time/@content'),
        ( 'll.mit.edu',                     '//div[@class="news-full__date"]'),
        ( 'localsegye.co.kr',               '//div[@class="viewTitle"]/dl/dd[@style="right:0px;bottom:10px;position:absolute;"]' ),
        ( 'logsoku.com',                    '//div[@id="comments"]/dl[@id="1"]/dt/text()'),
        ( 'lokwannee.com',                  '//div[@id="post-info-left"]'),
        ( 'lucianne.com',                   '//div/p[@class="post-posted-by"]'),
        ( 'lvcdn.com',                      '//div[@class="article_attribute"]/span/text()'),
        ( 'lwn.net',                        '//div[@class="ArticleText"]/h2/following-sibling::text()[1]'),
        ( 'lxbird.com',                     '//div[@class="jsx-854068075 time"]/text()'),
        ( 'macaudailytimes.com.mo',         '//div[@class="meta-data"]' ),
        ( 'maghress.com',                   '//span[@class="articlenewspaper"]'),
        ( 'malaymail.com',                  '//div/p[@class="meta mb-0"]'),
        ( 'manilastandard.net',             '//div[@class="ts-article-author-container"]' ),
        ( 'maritimejournal.com',            '//div[@class="news__published"]'),
        ( 'marsecreview.com',               '//time'),
        ( 'masjed.ir',                      '//span[@class="head2"]' ),
        ( 'masjed.ir',                      '//span[@id="ctl00_cphMiddle_Sampa_Web_View_NewsAgencyUI_NANewsDetail00cphMiddle_27244_lblDateTop"]' ),
        ( 'masjed.ir',                      '//span[@id="ctl00_cphMiddle_Sampa_Web_View_NewsAgencyUI_NANewsDetail00cphMiddle_27244_lblDateTop"]'),
        ( 'mauinews.com',                   '//aside[@id="article_details"]/time'),
        ( 'mda.mil',                        '//span[@class="DateTimeFormat"]'), # finds date, but can't parse
        ( 'mediamatters.org',               '(//p[@class="dateline"])[1]/time/@datetime' ),
        ( 'medienwerkstatt-online.de',      '//meta[@name="dc.date"]/@content'),
        ( 'medworm.com',                    '(//time)[1]'),
        ( 'mei.edu',                        '//date[@class="post__date"]'),
        ( 'mic.com',                        '//time/@datetime'),
        ( 'michelinfo.com',                 '//span[@class="post-date updated"]/text()'),
        ( 'miit.gov.cn',                    '//div[@class="short_r"]/text()'),
        ( 'militarytimes.com',              '//meta[@itemprop="datePublished"]/@content'),
        ( 'minnesota.cbslocal.com',         '//time[@class="timestamp"]/@datetime' ),
        ( 'minwonnews.com',                 '(//div[@class="info_area"]/span[@class="date"]/span)[1]' ),
        ( 'mixonline.jp',                   '//span[@id="dnn_ctr389_ArticleDetail_lblReleaseDateTime"]/text()'),
        ( 'modellversium.de',               '//p[@class="center"]/em'),
        ( 'moneys.mt.co.kr',                '//meta[@property="article:published_time"]/@content'),
        ( 'moneys.mt.co.kr',                '//span[@id="pn_article_date"]'),
        ( 'monitordolar.com',               '//time[@class="entry-date"]/@datetime' ),
        ( 'mothership.sg',                  '//div[@class="publish-info"]/p/span[@class="publish-date"]' ),
        ( 'mrctv.org',                      '//time/@datetime' ),
        ( 'mumbaimirror.indiatimes.com',    '//div[@class="left"]/span[@class="byline"]' ),
        ( 'mundiario.com',                  '//span[@class="content-time"]' ),
        ( 'mykaraokecafe.com',              '//div[@class="entry-meta"]/h5[@class="entry-date"]/time[@datetime="entry-date"]' ),
        ( 'mykaraokecafe.com',              '//time/@datetime' ),
        ( 'nachrichten.de',                 '//div[@class="article-bar"]/text()'),
        ( 'nato.int',                       '//ul[@class="list-meta"]/li'),
        ( 'naegeleblog.wordpress.com',      '//small[@class="date"]' ), 
        ( 'napolitoday.it',                 '//time[@class="datestamp"]' ),
        ( 'nas.org',                        '//div[@class="title-container"]/p'), #FIXME: there's lots of other article types not captured here
        ( 'nas.org',                        '//div[@class="medium-4 cell blog-single-left"]//li'),
        ( 'nationalpost.com',               '//span[@class="published-date__since"]'),
        ( 'nationalpost.com',               '//span[@class="published-date__since"]/@date-last-update'),
        ( 'nationalpost.com',               '//time[@itemprop="datePublished"]/@datetime'),
        ( 'nature.com',                     '//header//time[@datetime]'),
        ( 'nature.com',                     '//time[@itemprop="datePublished"]'),
        ( 'navalgazing.net',                '//div[@class="date"]'),
        ( 'nazanin.es',                     '//p[@class="postmetadata"]' ),
        ( 'nbc12.com',                      '//meta[@name="date"]/@content'),
        ( 'nbcnews.com',                    '//meta[@itemprop="datePublished"]/@content'),
        ( 'nbcnews.com',                    '//meta[@property="article:published_time"]/@content' ),
        ( 'nbcnews.com',                    '//span[@class="byline___3V_nz"]'),
        ( 'ncnews.com.cn',                  '//span[@class="newstime"]'),
        ( 'netzpolitik.org',                '//time[contains(@class,"published")]'),
        ( 'newindianexpress.com',           '(//p[@class="ArticlePublish margin-bottom-10"]/span)[1]'),
        ( 'news.biglobe.ne.jp',             '//p[@class="date"]' ),
        ( 'news.bioon.com',                 '//div[@class="title5"]/p/text()'),
        ( 'news.bitcoin.com',               '//time[@class="article__info__date"]'),
        ( 'news.china.com',                 '//div[@class="chan_newsInfo_source"]/span[@class="time"]' ),
        ( 'news.columbia.edu',              '//article/header/div'),
        ( 'news.com.au',                    '//meta[@itemprop="datePublished"]/@content'),
        ( 'news.denfaminicogamer.jp',       '//div[@class="entryMeta flxBox"]/time/@datetime'),
        ( 'news.goo.ne.jp',                 '//p[contains(@class,"article-date")]' ),
        ( 'news.grabien.com',               '//div[@class="storydate"]'),
        ( 'news.ifeng.com',                 '//div[@class="info-3ivibuHH clearfix"]/p[@class="time-hm3v7ddj"]/span' ),
        ( 'news.kakaku.com',                '//p[@class="date"]' ),
        ( 'news.livedoor.com',              '//div[@class="topicsHeaderBtm"]/time[@class="topicsTime"]' ),
        ( 'news.mt.co.kr',                  '//meta[@property="article:published_time"]/@content'),
        ( 'news.mt.co.kr',                  '//span[@id="pn_article_date"]'),
        ( 'news.nicovideo.jp',              '//time[@class="article-created-at"]'),
        ( 'news.so-net.ne.jp',              '(//ul[@class="dateAndSource wd440 clearfix"]/li)[1]'),
        ( 'news.un.org',                    '//meta[@property="article:published_time"]/@content' ),
        ( 'news.un.org',                    '//span[@property="dc:date"]/@content' ),
        ( 'news100.gguk.fun',               '//em[id="post-date"]/text()'),
        ( 'newscientist.com',               '//span[contains(@class,published-date)]'),
        ( 'newslocker.com',                 '//time[@class="entry-time"]/@datetime'),
        ( 'newsmir.info',                   '//span[@class="meta_date"]/a/text()'),
        ( 'newsoneplace.com',               '//span[@class="textlogoarticle"]/time/@datetime'),
        ( 'newswars.com',                   '//div[@class="entry-meta"]'),
        ( 'newswithviews.com',              '//div[@class="fusion-meta-info-wrapper"]/span'),
        ( 'niconews55.com',                 '//header[@class="article-header entry-header"]/p[@class="byline entry-meta vcard cf"]/time[@class="date gf entry-date updated"]'),
        ( 'niid.go.jp',                     '//time[@itemprop="datePublished"]/@datetime'),
        ( 'nk.jiho.jp',                     '(//span[@class="date-display-single"])[1]' ),
        ( 'nklogin.com',                    '//div[@class="pull-left"]/span[@style=" font-size: 0.9em;padding-left: 20px;"]'),
        ( 'noozhawk.com',                   '//div[@class="posted"]'),
        ( 'noozhawk.com',                   '//div[@class="timestamp"]'),
        ( 'nordbayern.de',                  '//meta[@name="Date"]/@content'),
        ( 'northkoreatimes.com',            '//div[@class="banner-section"]/p'),
        ( 'noticieros.televisa.com',        '//div[@class="video-post-title"]/div[@class="author"]'),
        ( 'noticieros.televisa.com',        '//meta[@property="article:published_time"]/@content'),
        ( 'novinite.com',                   '//div[@class="date"]'),
        ( 'nowthisnews.com',                '//p[@class="Bylinestyles__ArticleDate-sc-1dq0qrh-2 gqDify"]'),
        ( 'noxininfluencer.com',            '//p[@class="publised-date"]/text()'),
        ( 'npr.org',                        '//div[@class="dateblock"]/time/@datetime'),
        ( 'nrdc.org',                       '//span[contains(@class,"author-date")]'),
        ( 'nsf.gov',                        '//div[@class="authoring-information__date"]'),
        ( 'nsf.gov',                        '//div[@class="main__col  col-sm-12 col-md-12 col-lg-12"]/p/strong'),
        ( 'nsf.gov',                        '//span[@class="mediadate"]'),
        ( 'nsk.se',                         '(//time[@itemprop="datePublished"]/@datetime)[1]'),
        ( 'nvidianews.nvidia.com',          '//div[@class="article-date"]'),
        ( 'nydailynews.com',                '//meta[@name="date"]/@content'),
        ( 'nytimes.com',                    '//meta[@property="article:published"]/@content' ),
        ( 'nytimes.com',                    '//time[@class="css-129k401 e16638kd0"]/@datetime' ), # FIXME: these won't generalize?
        ( 'nytimes.com',                    '//time[@class="css-1sbuyqj e16638kd3"]/@datetime' ), # FIXME: these won't generalize?
        ( 'nzherald.co.nz',                 '//div[@class="video-date"]' ),
        ( 'nzherald.co.nz',                 '//meta[@name="article:published_time"]/@content' ),
        ( 'occrp.org',                      '//*[@class="date"]'),
        ( 'oinavi.com',                     '//p[@id="single-header-date"]/text()'),
        ( 'oluwagbemigapost.com',           '//time[@class="entry-date published updated"]/@datetime'),
        ( 'onenewspage.co.uk',              '//span[@class="lhpt"]'),
        ( 'onenewspage.com',                '//meta[@itemprop="uploadDate"]/@content'),
        ( 'opensource.org',                 '//div[@class="submitted"]'),
        ( 'oshiete.goo.ne.jp',              '//li[@class="date"]/time' ),
        ( 'ottawacitizen.com',              '//span[@class="published-date__since"]' ),
        ( 'ozap.com',                       '//div[@class="article__author-date"]' ),
        ( 'ozap.com',                       '//div[@class="article__author-date"]/text()'),
        ( 'papers.ssrn.com',                '//meta[@name="citation_online_date"]/@content' ),
        ( 'paragonie.com',                  '//time/@datetime'),
        ( 'parismatch.com',                 '//time/@datetime'),
        ( 'parismatch.com',                 '//time/@datetime'),
        ( 'patriotnewsdaily.com',           '//span[@class="tie-date"]'),
        ( 'pattayapeople.com',              '//div[@class="main"]/meta[@itemprop="datePublished"][@content]'),
        ( 'payvand.com',                    '//div[@class="article"]/meta[@content="text/html; charset=utf-8"]' ),
        ( 'people.com',                     '//div[@class="timestamp published-date padding-12-left"]' ),
        ( 'people.com.cn',                  '//meta[@name="publishdate"]/@content' ),
        ( 'periodicodebate.com',            '//div[@class="itemDateCreated"]' ),
        ( 'periodicodebate.com',            '//span[@class="itemDateCreated"]' ),
        ( 'persee.fr',                      '//meta[@itemprop="datePublished"]/@content'),
        ( 'pgr21.com',                      '(//table[@class="viewTable"]/tbody/tr/td)[2]' ),
        ( 'pharmacon.net',                  '//p[@align="right"]/font[@size="1"]/text()'),
        ( 'phoronix.com',                   '//div[@class="author"]/text()'),
        ( 'plaza.rakuten.co.jp',            '//div[@id="diarydate"]/b' ),
        ( 'plaza.rakuten.co.jp',            '//div[@id="diarydate"]/b'),
        ( 'pmnewsnigera.com',               '//div[@class="col-md-12 post"]/p[@class="time"]'),
        ( 'pmo.gov.sg',                     '//div[@class="meta-table"]/text()'),
        ( 'polisci.mit.edu',                '//span[@class="postdate"]'),
        ( 'politico.com',                   '//p[@class="story-meta__timestamp"]/time/@datetime'),
        ( 'politico.com',                   '//span[@class="timestamp"]'),
        ( 'politico.com',                   '//time[@itemprop="datePublished"]/@datetime'),
        ( 'politicususa.com',               '//a/time[@class="entry-date published updated"]/@datetime'),
        ( 'pourquoidocteur.fr',             '//div[@class="date mb10"]'),
        ( 'prachatai.com',                  '//span[@class="submitted-by"]'),
        ( 'prageru.com',                    '//time[@class="css-1e2zvr8 e1f0u4tf6"]' ),
        ( 'pressafrik.com',                 '//div[@class="access"]' ),
        ( 'projectveritas.com',             '//time[@class="css-bm1bwp ekxyxev2"]' ),
        ( 'prophecynewswatch.com',          '//span[@class="format"]'),
        ( 'prtimes.jp',                     '//time[@class="time icon-time-release-svn"]/@datetime' ),
        ( 'pttcomic.com',                   '//span[@class="post-time"]'),
        ( 'ptthito.com',                    '//meta[@name="description"]/@content'),
        ( 'public-security.de',             '//tr[@height="618"]/td[@valign="top"]/p/font[@color="#920054"]/strong'),
        ( 'public.fr',                      '//time/@datetime'),
        ( 'pulsoslp.com.mx',                '//time[@class="entry-date updated td-module-date"]/@datetime' ),
        ( 'qz.com',                         '//time/@datetime' ),
        ( 'rand.org',                       '//aside//li'),
        ( 'rand.org',                       '//p[@class="date"]'),
        ( 'realclearpolitics.com',          '//div[@class="byline"]'),
        ( 'realnewsrightnow.com',           '//meta[@property="article:published_time"]/@content'),
        ( 'religion.info',                  '//p[@class="entry-meta print-only"]'),
        ( 'renegadetribune.com',            '//span[@class="posted-on"]/time/@datetime' ),
        ( 'research.swtch.com',             '//div[@class="when"]'),
        ( 'researchgate.net',               '//meta[@itemprop="datePublished"]/@content'),
        ( 'resources.infosecinstitute.com', '//span[@class="date"]'),
        ( 'resumenlatinoamericano.org',     '//span[@class="post-byline"]' ),
        ( 'resumenmediooriente.org',        '//time[@class="entry-date"]/@datetime'),
        ( 'rila.org',                       '//header//li'),
        ( 'robert-schuman.eu',              '//div[@class="date"]'),
        ( 'roc-taiwan.org',                 '//div[@class="row"]/div[@class="col-sm-6 col-md-6 content-date"]'),
        ( 'ronpaulinstitute.org',           '//div[contains(@class,"post-date")]'),
        ( 'rsaconference.com',              '//time'),
        ( 'rtbf.be',                        '//meta[@itemprop="datePublished"]/@content'),
        ( 'rtl.be',                         '//span[@itemprop="datePublished"]/text()'),
        ( 'rtl.fr',                         '//div[@class="article-info"]/time/@datetime'),
        ( 'rts.ch',                         '(//span[@class="sc-141f4yq-6 cksdVr"])[1]'),
        ( 'ruhrnachrichten.de',             '//meta[@itemprop="datePublished"]/@content'),
        ( 'russiamatters.org',              '//div[@class="node__published"]'),
        ( 'russian.news.cn',                '//div[@class="info"]/text()'),
        ( 'russiancouncil.ru',              '//div[@class="date"]'),
        ( 'russland.news',                  '//abbr[@itemprop="datePublished"]/@title'),
        ( 'ruthfullyyours.com',             '//div/p[@id="single-byline"]'),
        ( 'ruthinstitute.org',              '//h4'),
        ( 'ryt9.com',                       '//p[@class="date-time"]'),
        ( 'salon.com',                      '//meta[@property="article:published_time"]/@content'),
        ( 'sana.sy',                        '//meta[@property="article:published_time"]/@content' ),
        ( 'sandia.gov',                     '//span[@class="entry-date"]' ),
        ( 'sandia.gov',                     '//span[@class="entry-date"]/abbr/@title' ),
        ( 'santemagazine.fr',               '//time/@datetime'),
        ( 'saymar.org',                     '//span[@class="tie-date"]/text()'),
        ( 'schleibinger.com',               '(//address/i/text())[1]'),
        ( 'schleibinger.com',               '//address/i/text()'),
        ( 'schneier.com',                   '//li[@class="pubdate"]'),
        ( 'schneier.com',                   '//p[@class="posted"]/a'),
        ( 'scholar.harvard.edu',            '//div[@class="node-content"]/i'),
        ( 'sciencealert.com',               '//div[contains(@class,"author-name-date")]'),
        ( 'sciencedirect.com',              '//div[@class="wrapper"]/p' ),
        ( 'sciencedirect.com',              '//meta[@name="citation_online_date"]/@content'),
        ( 'scienceillustrated.com.au',      '//p[@class="hentry-meta-data"]/text()'),
        ( 'sciencepress.qc.ca',             '(//font[@size="-1"]/text())[1]'),
        ( 'sciencepress.qc.ca',             '(//font[@size="-1"]/text())[1]'), 
        ( 'sciencepress.qc.ca',             '(//font[@size="-1"]/text())[1]'), 
        ( 'scientific.at',                  '//p[@align="right"]'),
        ( 'scmp.com',                       '//meta[@property="article:published_time"]/@content' ),
        ( 'scmp.com',                       '//time/@datetime' ),
        ( 'scotsman.com',                   '//div[@class="sc-bbkauy cshaXl"]' ),
        ( 'secureworld.io',                 '//div[@class="publish-date"]'),
        ( 'securitepublique.gc.ca',         '//meta[@name="dcterms.issued"]/@content'),
        ( 'securityweek.com',               '//div[@class="submitted"]/div/text()'),
        ( 'sedaily.com',                    '//li[@class="letter"]'),
        ( 'sedaily.com',                    '//meta[@property="dd:published_time"]/@content'),
        ( 'seekhlopakistan',                '(//time[@class="entry-date published updated"]/@datetime)[1]'),
        ( 'senenews.com',                   '//span[@class="date updated"]'),
        ( 'senenews.com',                   '//span[@class="date updated"]'),
        ( 'senenews.com',                   '//span[@class="timeT"]' ),
        ( 'sfc.hk',                         '(//small[@style="font-size: 11px; line-height: 18px;"]/text())[1]'),
        ( 'sg.news.yahoo.com',              '//time[@class="date Fz(11px) Mb(4px)  D(ib)"]'),
        ( 'sinpermiso.info',                '//meta[@name="dcterms.date"]/@content' ),
        ( 'siouxcountyradio.com',           '//p[@class="card-text text-muted"]/text()'),
        ( 'sipri.org',                      '//div[@class="content"]//time/@datetime'),
        ( 'skd.se',                         '(//time[@itemprop="datePublished"]/@datetime)[1]'),
        ( 'skynews.com.au',                 '//span[@class="metadata-date"]'),
        ( 'slateafrique.com',               '//time/@datetime'),
        ( 'smartprices.org',                '//time[@class="entry-time"]/@datetime' ),
        ( 'smartraveller.gov.au',           '//div[@class="clearfix text-formatted field field—name-field-body field—type-text-long field—label-hidden field__item"]/p' ),
        ( 'smithsonianmag.com',             '//time/@data-pubdate' ),
        ( 'smnyct.org',                     '(//small/text())[1]'),
        ( 'smolensk2.ru',                   '//p[@class="xfolkentryHeaderMeta"]/time[@class="xfolkentryTime"]/@datetime'),
        ( 'smw.ch',                         '//meta[@name="dc.date"]/@content'),
        ( 'snopes.com',                     '//li/span[@class="date date-published"]'),
        ( 'soakaeofh.egloos.com',           '//abbr[@class="published"]/@title'),
        ( 'sofmag.com',                     '//span[@class="tie-date"]' ),
        ( 'sofmag.com',                     '//span[@class="tie-date"]/i[@class="fa fa-clock-o"]' ),
        ( 'sohfrance.org',                  '//meta[@property="article:published_time"]/@content' ),
        ( 'soundcloud.com',                 '//time[@class="relativeTime"]/@datetime'),
        ( 'sp.m.jiji.com',                  '//div[@class="newsArticle__date"]/text()'),
        ( 'spectrum.ieee.org',              '//div[@class="published-date hide-mobile"]'),
        ( 'spectrum.ieee.org',              '//div[contains(@class,"published-date")]'),
        ( 'spf.org',                        '(//div[@id="unit-3671"]/p)[19]'),
        ( 'spiegel.de',                     '//span[@class="article-function-date"]/b' ),
        ( 'spiegel.de',                     '//time/@datetime' ),
        ( 'stratcomcoe.org',                '//p[@class="date"]'),
        ( 'state.gov',                      '//p[@class="article-meta__publish-date"]' ),
        ( 'steelorbis.com',                 '//div[@class="col-sm-8 col-md-9"]' ),
        ( 'sternchen4you.de',               '//time[@class="entry-date published"]/@datetime'),
        ( 'strategypage.com',               '//span[@class="meta_date"]'),
        ( 'streetpress.com',                '//span[@class="date has-text-yellow"]'),
        ( 'stripes.com',                    '//span[@class="article_credits small-16 columns"]' ),
        ( 'stripes.com',                    '//span[@class="published_date"]' ),
        ( 'studymode.com',                  '//span[@class="essay-details--grey text-s"]' ),
        ( 'sudouest.fr',                    '//time/@datetime'),
        ( 'sumedico.lasillarota.com',       '//li[@class="far fa-calendar-all"]/text()'),
        ( 'sumedico.lasillarota.com',       '//ul[@class="data-note"]'),
        ( 'sygnia.co',                      '//p[@class="p ap-author"]'),
        ( 'talosintelligence.com',          '//*[@class="date_time"]'),
        ( 'tdg.ch',                         '//time/@datetime'),
        ( 'tdg.ch',                         '//time[@class="full-date-time"]/@datetime' ),
        ( 'tdg.ch',                         '//time[@class="last-updated-date-time"]/@datetime' ),
        ( 'tdg.ch',                         '//time[@class="last-updated-date-time"]/@datetime'),
        ( 'techdirt.com',                   '//span[@class="pub_date"]'),
        ( 'techrepublic.com',               '//span[@class="byline-item"]' ),
        ( 'tectalk.co',                     '//div[@class="post-byline"]'),
        ( 'ted.com',                        '//meta[@itemprop="uploadDate"]/@content'),
        ( 'telegraph.co.uk',                '//*[@itemprop="datePublished"]/@content' ),
        ( 'telegraph.co.uk',                '//meta[@itemprop="datePublished"]/@content'),
        ( 'telemazonas.com',                '(//time[@class="updated"]/@datetime)[1]' ),
        ( 'theatlanic.com',                 '//div[@id="article-header"]/ul[@class="metadata"]/li[@class="date"]'),
        ( 'thebigwobble.org',               '//div[@class="date-outer"]//h2[@class="date-header"]/span' ),
        ( 'thecipherbrief.com',             '//time/@datetime' ),
        ( 'thecitizen.org.au',              '//datetime'),
        ( 'thedailybeast.com',              '//time/@datetime' ),
        ( 'thedailygrind.news',             '//meta[@name="date"]/@content'),
        ( 'theday.co.uk',                   '//time[@id="published-at"]/@datetime'),
        ( 'thediplomat.com',                '//span[@itemprop="datePublished"]' ),
        ( 'thefreelibrary.com',             '//table[@style="width:100%;border-spacing:0;border:none"]/tbody/tr[@class="odd"]/td/a'),
        ( 'theinitium.com',                 '//time[@class="posted-time"]/@datetime'),
        ( 'theintercept.com',               '//span[@class="PostByline-date"]' ),
        ( 'thelibertybeacon.com',           '//span[@class="entry-meta-date updated"]/a'),
        ( 'themillenniumreport.com',        '//time/@datetime'),
        ( 'thenational.ae',                 '(//div[@class="desc-box"]/div[@class="hidden-lg"]/p)[1]'),
        ( 'thenewamerican.com',             '//span[@class="itemDateCreated"]' ),
        ( 'thenewscommenter.com',           '//article[@class="story detail-page"]//div[@class="col-xs-12"]/p' ),
        ( 'thepeoplescube.com',             '(//article[@id="content"]/div[@class="nounder"])[1]'),
        ( 'thepopculturecompany.com',       '(//tbody/tr)[2]' ),
        ( 'thetimes.co.uk',                 '//article[@id="article-main"]//time/@datetime' ),
        ( 'thetrumpet.com',                 '(//p[@class="article-byline"])[1]' ),
        ( 'theunitedwest.org',              '(//time[@class="entry-date updated td-module-date"]/@datetime)[1]'),
        ( 'thevoiceofchinese.com',          '//span[@class="entry-meta-date updated"]/a'),
        ( 'theworldnews.net',               '//span[@class="news__time"]/text()'),
        ( 'thinkprogress.org',              '//time[@class="post__date"]/@datetime'),
        ( 'thoughtco.com',                  '//div[@class="comp updated-label article-updated-label"]'),
        ( 'threadreaderapp.com',            '//a[@class="time"]/@data-time'),
        ( 'time.com',                       '//div[contains(@class,"published-date")]' ),
        ( 'timesofindia.indiatimes.com',    '//b/@dateval'),
        ( 'timesofisrael.com',              '//div[@class="wrap-byline"]/span[@class="date"]' ),
        ( 'tmz.com',                        '//h5[@class="article__published-at"]' ),
        ( 'today.it',                       '//time[@class="datestamp"]'),
        ( 'todotexcoco.com',                '//time/text()'),
        ( 'tonibitt.blogia.com',            '//time/@datetime'),
        ( 'toonippo.co.jp',                 '//div[@id="signage"]/div[@class="pubdate"]' ),
        ( 'topia.ne.jp',                    '//p[@class="publishedAt"]/text()'),
        ( 'torindiegalaxien.de',            '//p[@class="MsoNormal"]/em/span/a'),
        ( 'touteleurope.eu',                '(//span[@class="date"])[1]' ),
        ( 'touteleurope.eu',                '(//span[@class="date"]/text())[1]'),
        ( 'townhall.com',                   '//div[@class="contributor pull-left"][contains(.,"Posted:")]/text()'),
        ( 'treasury.gov',                   '//div[@class="content-slim"]/br'),
        ( 'treasury.gov',                   '//div[@class="updated"]'),
        ( 'trend.infopartisan.net',         '//td[@align="left"]/font[@size="1"]/span[@lang="de"]'),
        ( 'tresor.economic.gouv.fr',        '//time/@datetime'),
        ( 'tribuna.ucm.es',                 '//span[@class="fechaarticulo"]/text()'),
        ( 'trumancenter.org',               '//div[@class="blog-date"]'),
        ( 'trt.net.tr',                     '//div[@class="col-sm-12 col-lg-6"]/time'),
        ( 'trtworld.com',                   '//ul[@class="author"]'),
        ( 'tvanouvelles.ca',                '(//time[@itemprop="datePublished"]/@datetime)[1]' ),
        ( 'tvanouvelles.ca',                '//span[@class="strong-date"]/time/@datetime'),
        ( 'ultimahora.hn',                  '//span[@property="dc:date dc:created"]/@content'),
        ( 'unadfi.org',                     '//time[@class="entry-date published updated"]/@datetime'),
        ( 'unis.unvienna.org',              '//meta[@name="creation-date"]/@content'),
        ( 'unitypublishing.com',            '//span[@style="font-size:13.5pt"]' ),
        ( 'universalis.fr',                 '//span[@class="rg"]'),
        ( 'unz.com',                        '//div[@class="byline"]/span[@class="datewords"]'),
        ( 'urdupoint.com',                  '//span[@class="article-date"]'),
        ( 'usatoday.com',                   '//p[@class="header__pubdate svelte-1t1csty"]/text()'),
        ( 'usatoday.com',                   '//story-timestamp[@id="videoTimestamp"]/text()'),
        ( 'usc.edu.tw',                     '//span[@class="s-annc__date"]' ),
        ( 'uscirf.gov',                     '//p[@class="news-date"]'),
        ( 'usip.org',                       '//header[@class="page__header"]/p[@class="meta"]'),
        ( 'ut-capitole.fr',                 '//meta[@name="Date-Creation-yyyymmdd"]/@content'),     
        ( 'valeursactuelles.com',           '//span[@class="rdf-meta hidden"]/@content' ),
        ( 'valeursactuelles.com',           '//span[@property="schema:dateCreated"]/@content'),
        ( 'valeursactuelles.com',           '//span[@property="schema:dateCreated"]/@content'),
        ( 'vanityfair.com',                 '//time[@class="content-header__publish-date"]'),
        ( 'varlamov.ru',                    '//span[@class="j-e-date"]/time[@itemprop="datePublished"]'),
        ( 'verlag-dr.de',                   '//span[@style="color: #000000"]/text()'),
        ( 'videos.telesurtv.net',           '//time/@datetime'),
        ( 'vie-publique.fr',                '(//time/@datetime)[1]'),
        ( 'vie-publique.fr',                '//p[@class="dateBox"]/span[@class="field field--name-field-date-remise field--type-datetime field--label-hidden field__item"]/time/@datetime'),
        ( 'virosin.org',                    '//meta[@name="dc.date"]/@content'),
        ( 'virusncov.com',                  '(//small/text())[1]'),
        ( 'vitaminedz.com',                 '//div[@class="social_link"]/text()'),
        ( 'voaafrique.com',                 '(//span[@class="date"]/time/@datetime)[1]' ),
        ( 'voanews.com',                    '//div[@class="page-header__meta-item"]'),
        ( 'voxeurop.eu',                    '//div[contains(@class,"publish_date_time")]' ),
        ( 'vvvreevvv.info',                 '//time[@class="updated"]/@datetime'),
        ( 'waffenexporte.de',               '//td[@class="obenrechts"]/text()'),
        ( 'wajr.com',                       '//time[@class="published"]/@datetime'),
        ( 'wanweibaike.com',                '(//div[@class="foot"]/p/text())[1]'),
        ( 'washingtoninstitute.org',        '(//header[@class="tight-paragraphs tertiary-header group"]/p)[5]'),
        ( 'washingtoninstitute.org',        '//div[@class="date pr-8"]'),
        ( 'washingtonpost.com',             '//div[@class="display-date"]'),
        ( 'washingtonpost.com',             '//div[@class="metaData margin-bottom"]/span[@class="date"]'),
        ( 'washingtonpost.com',             '//meta[@name="recv_time"]/@content'),
        ( 'wbal.com',                       '//div[@class="disclaimer"]'),
        ( 'weekly.cnbnews.com',             '//p[@class="arvdate"]/text()'),
        ( 'wenxuecity.com',                 '//div[@id="postmeta"]/time[@itemprop="datePublished"]' ),
        ( 'whitehouse.gov',                 '//p[@class="meta__date"]/time'),
        ( 'wiete-strafrecht.de',            '//span[@style="font-style: italic;"]/text()'),
        ( 'wiki2.org',                      '//div[@class="last_mod"]/text()'),
        ( 'wilsoncenter.org',               '//span[@class="insight-detail-hero-author-byline-text -date"]'),
        ( 'wionews.com',                    '//div[@class="col-sm-8"]/div[@class="new-loc-date-stamp"]/span'),
        ( 'wired.com',                      '//time[@class="content-header__publish-date content-header__title-block-publish-date"]'),
        ( 'wired.com',                      '//time[@class="date-mdy"]'),
        ( 'wjw.putian.gov.cn',              '//h5[@class="ly"]/em'),
        ( 'wluml.org',                      '/div[@class="meta"]/div[@class="submitted"]' ),
        ( 'works.medical.nikkeibp.co.jp',   '//span[@itemprop="datePublished"]/text()'),
        ( 'wright-house.com',               '//font[@size="+1"]/b' ),
        ( 'wsj.com',                        '//meta[@itemprop="datePublished"]/@content'),
        ( 'wsj.com',                        '//span[@class="published"]/text()'),
        ( 'wuhanupdate.com',                '//time[@class="entry-time"]/@content'),
        ( 'xbuy.info',                      '//time[@class="entry-time"]/@datetime' ),
        ( 'xxmishu.com',                    '//div[@class="delivery-time"]/span' ),
        ( 'yahoo.com',                      '//time/@datetime' ),
        ( 'yemen-direct.com',               '//div[@class="news-date-info"]/span[@class="story_date"]'),
        ( 'youthdaily.co.kr',               '(//ul[@class="art_info"]/li/text())[1]'),
        ( 'youtube.com',                    '//div[@id="date"]/yt-formatted-string[@class="style-scope ytd-video-primary-info-renderer"]'),
        ( 'yq.aliyun.com',                  '//div[@class="blog-o-info"]/span[@class="b-time icon-shijian1"]/text()'),
        ( 'yunjuu.com',                     '(//span[@class="entry-date"]/text())[1]'),
        ( 'zataz.com',                      '//div[@class="blog-info-wrapper gdl-item-border"]/div[@class="blog-date"]/a'),
        ( 'zdnet.com',                      '(//time/@datetime)[1]'),
        ( 'zdnet.fr',                       '//time/@datetime'),
        ( 'zzzzz.de',                       '//small/text()'),

        # universal xpaths
        ( None, '//meta[@*="ArticlePublishDate"]/@content'),
        ( None, '//meta[@*="DATE"]/@content' ),
        ( None, '//meta[@*="DCTERMS.issued"]/@content' ),
        ( None, '//meta[@*="OriginalPublicationDate"]/@content' ),
        ( None, '//meta[@*="PublishDate"]/@content' ),
        ( None, '//meta[@*="all_timestamps"]/@content' ),
        ( None, '//meta[@*="article:post_date"]/@content' ),
        ( None, '//meta[@*="article:published"]/@content'),
        ( None, '//meta[@*="article:published_time"]/@content' ),
        ( None, '//meta[@*="article_date_original"]/@content' ),
        ( None, '//meta[@*="cXenseParse:recs:publishtime"]/@content' ),
        ( None, '//meta[@*="date"]/@content' ),
        ( None, '//meta[@*="dc.Date"]/@content' ),
        ( None, '//meta[@*="dcterms.created"]/@content' ),
        ( None, '//meta[@*="dcterms.date"]/@content' ),
        ( None, '//meta[@*="og:article:published_time"]/@content' ),
        ( None, '//meta[@*="og:published_time"]/@content' ),
        ( None, '//meta[@*="parsely-pub-date"]/@content' ),
        ( None, '//meta[@*="pubdate"]/@content' ),
        ( None, '//meta[@*="pubdate"]/@datetime' ),
        ( None, '//meta[@*="publication_date"]/@content' ),
        ( None, '//meta[@*="publishdate"]/@content'),
        ( None, '//meta[@*="publish-date"]/@content'),
        ( None, '//meta[@*="published_time_telegram"]/@content'),
        ( None, '//meta[@*="recv_time"]/@content'),
        ( None, '//meta[@*="rnews:datePublished"]/@content' ),
        ( None, '//meta[@*="sailthru.date"]/@content' ),
        ( None, '//meta[@*="uploadDate"]/@content'),

        ( None, '//meta[@name="mediator_published_time"]/@content'),

        # microdata paths
        ( None, '//*[@itemprop="datePublished"]/@content' ),
        ( None, '//*[@itemprop="datePublished"]/@datetime' ),
        ( None, '//*[@property="datePublished"]/@content' ),
        ( None, '//*[@property="datePublished"]/@datetime' ),

        ]

    regexes = [
        ( 'herodote.net', r'[\./\-_](\d{8})[\./\-_]' ),
        ( 'lewis.armscontrolwonk.com', r'intentionally disabled' ),
        ( 'guests.armscontrolwonk.com', r'intentionally disabled' ),
        ( None, r'([\./\-_](19|20)\d{2}[\./\-_]+[0-1]?[0-9][\./\-_]+([0-3]?[0-9][\./\-_])?)' ),
        ( None, r'([\./\-_](19|20)\d{2}[\./\-_]+[a-zA-Z]{3}[\./\-_]+([0-3]?[0-9][\./\-_]))' ),
        #( None, r'([\./\-_](19|20)\d{2}[_]+[0-1]?[0-9][_]+([0-3]?[0-9][\./\-_])?)' ),
        #( None, r'([\./\-_](19|20)\d{2}[/]+[0-1]?[0-9][/]+([0-3]?[0-9][\./\-_])?)' ),
        #( None, r'([\./\-_](19|20)\d{2}[\-]+[0-1]?[0-9][\-]+([0-3]?[0-9][\./\-_])?)' ),
        #( None, r'([\./\-_](19|20)\d{2}[\.]+[0-1]?[0-9][\.]+([0-3]?[0-9][\./\-_])?)' ),
        #( None, r'([\./\-_](19|20)\d{2}[_]+[a-zA-Z]{3}[_]+([0-3]?[0-9][\./\-_]))' ),
        #( None, r'([\./\-_](19|20)\d{2}[/]+[a-zA-Z]{3}[/]+([0-3]?[0-9][\./\-_]))' ),
        #( None, r'([\./\-_](19|20)\d{2}[\-]+[a-zA-Z]{3}[\-]+([0-3]?[0-9][\./\-_]))' ),
        #( None, r'([\./\-_](19|20)\d{2}[\.]+[a-zA-Z]{3}[\.]+([0-3]?[0-9][\./\-_]))' ),
        ]
